### ISSUE TITLE
Smart App Banners

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-splash#5]
https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by sachabest** [comment]
Thanks

**Comment by adelq** [comment]
I just added a pull request for this, though I'm not sure anymore if it's worth cluttering up the page with yet another banner. Thoughts?
